apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d4wf21i6v-nodejs
  janus-idp.io/tekton: d4wf21i6v-nodejs
  backstage.io/kubernetes-id: d4wf21i6v-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d4wf21i6v-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
